name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: |
          uname -a
          ldd --version
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev
      - name: Build
        run: cargo build
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: |
          uname -a
          ldd --version
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          rustup toolchain install nightly --allow-downgrade -c rustfmt
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Check
        run: cargo +nightly fmt -- --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: |
          uname -a
          ldd --version
      - name: Install
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev
      - name: Test
        run: cargo test
